import os

Import('env')

env.SharedLibrary(target = 'SimpleService', source = ['SimpleService.cc'],
    LIBS = ['IARnet', env['LIBS']])

testEnv = env.Clone(ENV = {'PATH' : os.environ['PATH']})

testEnv.CxxTest('alltests', ['MaximaInstanceTest.h', '../src/MaximaInstance.cc'],
    CXXFLAGS='-Wall -W -Wextra',
    CPPPATH = '#', LIBS = ['boost_regex-mt', 'boost_filesystem-mt', 'boost_system-mt'],
    CPPDEFINES = [('MAXIMA_APP_PATH', '\\"${MAXIMA_APP}\\"'),
        ('MAXIMA_TEST_DIR', '\\"test\\"')])

