Import('env')

if env['ICE_ENABLE']:
    env.SConscript('IARnet/SConscript', exports = 'env')

if env['EVEREST_HOME']:
    env.SConscript('everest/SConscript', exports = 'env')

env.SConscript(dirs = ['MaximaAPI', 'jni'], exports = 'env')

